### ISSUE TITLE
UI for Handleglue is much needed

### ISSUE THREAD

**Issue by Tungee** [shspage/illustrator-scripts#2]
First of all, i thank you very much for your wonderful and super useful Illu Scripts.
I use them on a daily basis.

Now back to topic. An User Interface for the Handleglue is much needed, because i want use the angle option, but i dont know how to handle this?! I think also that the options should be there by default also in the Ui because every feature is needed often( Multi, angle, nearest)
Best regards

**Comment by shspage** [comment]
Thank you for using my script!
I'll consider how to add UI to handleGlue.jsx, using ScriptUI.
Actually, there is an HTML5 extension "handleGlue", which already has UI.
This is why I said "using ScriptUI".
You can use it if you have Illustrator CC or later.  It can be installed from Adobe Add-ons. (https://creative.adobe.com/addons).
If you are using CS, please wait for a while.

**Comment by Tungee** [comment]
Thank you very much Hiroyiku!
Im on CS4 and therefore i'll wait. 
Yesterday i looked into the code and changed it manualy to angle. Can i copy the skript and rename it to Handleglue_angle and the other one to Handleglue_nearest? I will test this.

PS.:
Hiroyiku i know you have a ton of skripts. Is there a one where the crossinfg of two paths get anchors?

Best Regards Tungee

**Comment by shspage** [comment]
It's a good idea that duplicating a script and providing different optional values to them.
In this case, you can shortcut the process that opening a dialog and clicking OK button.

Once I wrote a script that generates anchors at intersection points of straight lines and a curve.
In case of getting intersection points of two curves, I'm stuck in some unsolved problem.
Usually I use pathfinder when I want to get anchors at intersection point of paths.

**Comment by Tungee** [comment]
Yes it works nicely with different scripts :)

PS.: I needed this because, you could then reverse some rounded edges:
1. Clear the rounded edge
2. Extent the lines so they cross
3. produce a anchor on the crossing
4. connect

But i find these 2 nice scripts, to solve the problem:
http://www.pictrix.jp/ai/Re_Corner/
and
http://www.pictrix.jp/ai/collision/

which makes it very simple to "de-round"

Best Regards

**Comment by shspage** [comment]
>PS.:

I see. Those scripts look convenient!

**Comment by shspage** [comment]
I added GUI to handleGlue.jsx.
Would you please test it?

**Comment by Tungee** [comment]
Hiroyuki, wow that was blazing fast!! Wohoo :)
I tested it now: everything is working great!. I didnt test Multi and add anchor features before, but nearest and agle are working as expected.

![bildschirmfoto 2016-11-30 um 13 39 40](https://cloud.githubusercontent.com/assets/3286171/20752618/7c0eb802-b702-11e6-9891-4c8384d3d1e8.png)


Thank you very much!!!
Best Regards!

**Comment by shspage** [comment]
Thank you very much for testing.
While I modified this one, I got an idea to improve the extension version of this.
I close this issue.
