### ISSUE TITLE
Grass generation on the "wrong" side of the path

### ISSUE THREAD

**Issue by Tungee** [shspage/illustrator-scripts#4]
Hi Hiroyuki, i lately used your grass plugin to produce some fur and it worked very well. But i have a lot of cases where the grass wasnt on the right side of the path. I tried to reverse the path with your and other reversepath scripts but it had no eff

ect.
I prepared you some examples here:

![grass](https://cloud.githubusercontent.com/assets/3286171/22019589/782f7c4e-dcb4-11e6-8b10-6daff930dafc.png)

Here is the end result which i get with try-find-manner:

![bildschirmfoto 2017-01-17 um 13 04 32](https://cloud.githubusercontent.com/assets/3286171/22019854/89fe4b8e-dcb5-11e6-9d23-d5f7f82c7321.png)

It would be nice if we could have a invert button for to get the right side of the path!
Best Regards Tungee

**Comment by shspage** [comment]
Hi Tungee,
Thank you for your report.
It would be nice if it has a "invert" checkbox and a preview button.
I'll implement these.
For now, you can reverse the direction by editing the "height" value to be negative.
(i.e. edit 20 to -20)

In the present code, the grass direction is not determined by the direction of the path.
It is determined by angle of the lines between first three anchors - only when the path has 3 or more anchors. (at the part commented "// determine grow toward inside or outside".)
There may be other method, but there's no perfect way.
I'm sure no one can determine the "right" side for the curve in the attached image.
![github_issue4](https://cloud.githubusercontent.com/assets/3269510/22023069/04d0580a-dd08-11e6-8647-a41c283f2625.png)

**Comment by Tungee** [comment]
Ok Hiroyuke, i did not know, that a negative height value changes the grow direction! Thank you very much for your quick answer! I checked the docs and yes there is the negative height value. I must oversaw this. Perhaps you could add your last pic to the docs also?  Bytheway i lately  used your grass addon for fur, grass and petals.

Best Regards Tungee

**Comment by shspage** [comment]
Hi Tungee,
I uploaded modified "grass.jsx" which has an "invert" checkbox and a preview button.
I hope it works for you.

**Comment by Tungee** [comment]
Thank you very much Hiroyuke!
The invert does work nicely!

But like the round corner plugin the preview box makes the dialog unselectable anymore. The esc key helps here to go back to illustrator.

![bildschirmfoto 2017-01-18 um 19 02 12](https://cloud.githubusercontent.com/assets/3286171/22076595/0edbcb32-ddb1-11e6-9eaf-23234f3e7208.png)

its because im on Illustrator CS4 i think?!

best Regards Tungee

**Comment by Tungee** [comment]
Hiroyuke i also get this when i use to narrow widths:

![memory-leak](https://cloud.githubusercontent.com/assets/3286171/22077323/01745948-ddb4-11e6-89bc-756d7e13d34d.png)

**Comment by shspage** [comment]
Hi Tungee,
I updated the script to solve a dialog freeze issue.
It needs further investigation about the narrow width issue.
I guess it exceeds maximum array length.

**Comment by Tungee** [comment]
Hi Hiroyuke, the new script frezes too :(
Im on OSX if it helps.

![bildschirmfoto 2017-01-18 um 23 42 39](https://cloud.githubusercontent.com/assets/3286171/22086184/e69e538e-ddd7-11e6-84f8-a743ecaa157f.png)

Best Regards Tungee

**Comment by shspage** [comment]
Hi Tungee,
I'm sorry but I just can't reproduce it.

**Comment by Tungee** [comment]
No problem Hiroyuke, i thank you very much!
The Invert button is a life saver.
I think it must have to do something about my OSx and Cs4 version.
Best Regards Tungee

**Comment by shspage** [comment]
Hi Tungee,
I set an upper limit to the number of anchor points, to avoid an error "Invalid Argument".
A dialog appears when there are paths which exceed this limit. And these paths are not processed.

The dialog is grayed out while processing, in order not to allow user to manipulate it.
It may take several seconds.  This is not a state so-calld "freeze".

**Comment by Tungee** [comment]
Hi Hiroyuke, is it a ram issue for the "invalid argument"?

After its greyed out, i have only have two possibilities: Return to confirm or esc to abort.

Best Regards

**Comment by shspage** [comment]
The upper limit is 1000.
I guess it is specification of PathItem.setEntirePath().
I have nothing more to do with this issue now.

**Comment by Tungee** [comment]
Ok thank you Hiroyuke!
