### ISSUE TITLE
How to export any assets?Thanks.

### ISSUE THREAD

**Issue by pearl-he** [shspage/illustrator-scripts#5]
Hi Hiroyuki, Ther is a difficult problem. I need to traverse all the assets in a ai file and get their height and width,then exporting a  png file ,Do you have any idea?
Thanks.

**Comment by shspage** [comment]
I'm not familiar with assets. I have never even used it.
I recommend you to ask about it at the [Adobe's Illustrator Scripting Forum](https://forums.adobe.com/community/illustrator/illustrator_scripting) or any other similar site.

**Comment by pearl-he** [comment]
Thanks for the thought, anyway
